# Generated by Django 4.2.8 on 2023-12-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0003_employee_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="student_model",
            name="profile_pic",
            field=models.ImageField(null=True, upload_to="media/profile_pic"),
        ),
    ]
